In [60]:
print("hello")

hello


In [61]:
# check numpy version

import numpy as np 
np.__version__

'1.26.4'

In [62]:
list1 = [1, 2, 3, 4, 5]
# list1 = [1, 2, "3", 4, 5]       #output --> ['1' '2' '3' '4' '5']  

arr1 = np.array(list1)
print(arr1,type(arr1))

[1 2 3 4 5] <class 'numpy.ndarray'>


In [63]:
arr2 = np.arange(1,10)          #arange fun is similar to the in range fun
arr2

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [64]:
arr3 = np.ones(5)          #provides output in float datatype
arr3

array([1., 1., 1., 1., 1.])

In [65]:
arr4 = np.zeros((4, 5))        #2D array ---> (rows, columns)
arr4

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [66]:
arr5 = np.linspace(1, 10, 5)     #(start, stop, no of partions)
arr5

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [67]:
arr6 = np.arange(1, 31).reshape(5, 6)      #changes the 1D array into nD array, 
arr6                                        

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [68]:
arr7 = np.random.randint(1, 100, 10)          #(start, stop, no of partions)
arr7

array([80, 87, 98, 25, 43,  2, 10, 31, 94, 25])

In [69]:
arr8 = np.random.randint(1, 1000, 60).reshape(6, 10)
print(arr8.shape)                  #provides (rows, columns)
arr8.dtype                  #type of ele in an array
arr8.size                   #no of ele in an array
arr8.ndim                   #dimention of an array eg. 2d, 3d

arr9 = arr8.T               #transpose the matrix
print(arr9.shape)

(6, 10)
(10, 6)


In [70]:
#convert the multi dimentional array into 1d array
 
arr8.ravel()
arr8.flatten()

array([689, 151, 428, 551,  92, 244, 420, 626, 462, 878, 882, 134, 514,
       585, 709, 526, 249, 407, 538, 655, 649, 826, 717, 447, 187, 272,
       296,  17,  91, 857, 400, 437, 751, 868, 799, 691, 542, 446, 889,
       739, 444, 528, 378, 178, 217, 688, 909, 693,  81, 864, 469,  81,
       469, 132, 174, 246, 123, 227, 143, 595])

## Indexing and Slicing ##

In [86]:
arr2 = np.arange(1,10)

print(arr2[5])          #indexing
print(arr2[1::2])       #slicing
arr2

6
[2 4 6 8]


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#slicing in 2D array
 
arr9 = np.arange(0, 60).reshape(6, 10)

print(arr9[3:5,4:6][0][0])
print(arr9[::-1, ::-1])
arr9

34
[[59 58 57 56 55 54 53 52 51 50]
 [49 48 47 46 45 44 43 42 41 40]
 [39 38 37 36 35 34 33 32 31 30]
 [29 28 27 26 25 24 23 22 21 20]
 [19 18 17 16 15 14 13 12 11 10]
 [ 9  8  7  6  5  4  3  2  1  0]]


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [ ]:
arr10 = np.arange(225).reshape(5, 5, 9)           #(no of 2d matrix, rows, column)
arr10

array([[[  0,   1,   2,   3,   4,   5,   6,   7,   8],
        [  9,  10,  11,  12,  13,  14,  15,  16,  17],
        [ 18,  19,  20,  21,  22,  23,  24,  25,  26],
        [ 27,  28,  29,  30,  31,  32,  33,  34,  35],
        [ 36,  37,  38,  39,  40,  41,  42,  43,  44]],

       [[ 45,  46,  47,  48,  49,  50,  51,  52,  53],
        [ 54,  55,  56,  57,  58,  59,  60,  61,  62],
        [ 63,  64,  65,  66,  67,  68,  69,  70,  71],
        [ 72,  73,  74,  75,  76,  77,  78,  79,  80],
        [ 81,  82,  83,  84,  85,  86,  87,  88,  89]],

       [[ 90,  91,  92,  93,  94,  95,  96,  97,  98],
        [ 99, 100, 101, 102, 103, 104, 105, 106, 107],
        [108, 109, 110, 111, 112, 113, 114, 115, 116],
        [117, 118, 119, 120, 121, 122, 123, 124, 125],
        [126, 127, 128, 129, 130, 131, 132, 133, 134]],

       [[135, 136, 137, 138, 139, 140, 141, 142, 143],
        [144, 145, 146, 147, 148, 149, 150, 151, 152],
        [153, 154, 155, 156, 157, 158, 159, 160, 161],
    

In [ ]:
#slicing in 3D array syntax

#[table_start : table_end : table_skip , row_start : row_end , row_skip , column_start : column_end : column_skip]

arr10 = np.arange(225).reshape(5, 5, 9)
print(arr10[1:3])
print(arr10[1:3])
print(arr10[1:3])
arr10

[[[ 45  46  47  48  49  50  51  52  53]
  [ 54  55  56  57  58  59  60  61  62]
  [ 63  64  65  66  67  68  69  70  71]
  [ 72  73  74  75  76  77  78  79  80]
  [ 81  82  83  84  85  86  87  88  89]]

 [[ 90  91  92  93  94  95  96  97  98]
  [ 99 100 101 102 103 104 105 106 107]
  [108 109 110 111 112 113 114 115 116]
  [117 118 119 120 121 122 123 124 125]
  [126 127 128 129 130 131 132 133 134]]]


array([[[  0,   1,   2,   3,   4,   5,   6,   7,   8],
        [  9,  10,  11,  12,  13,  14,  15,  16,  17],
        [ 18,  19,  20,  21,  22,  23,  24,  25,  26],
        [ 27,  28,  29,  30,  31,  32,  33,  34,  35],
        [ 36,  37,  38,  39,  40,  41,  42,  43,  44]],

       [[ 45,  46,  47,  48,  49,  50,  51,  52,  53],
        [ 54,  55,  56,  57,  58,  59,  60,  61,  62],
        [ 63,  64,  65,  66,  67,  68,  69,  70,  71],
        [ 72,  73,  74,  75,  76,  77,  78,  79,  80],
        [ 81,  82,  83,  84,  85,  86,  87,  88,  89]],

       [[ 90,  91,  92,  93,  94,  95,  96,  97,  98],
        [ 99, 100, 101, 102, 103, 104, 105, 106, 107],
        [108, 109, 110, 111, 112, 113, 114, 115, 116],
        [117, 118, 119, 120, 121, 122, 123, 124, 125],
        [126, 127, 128, 129, 130, 131, 132, 133, 134]],

       [[135, 136, 137, 138, 139, 140, 141, 142, 143],
        [144, 145, 146, 147, 148, 149, 150, 151, 152],
        [153, 154, 155, 156, 157, 158, 159, 160, 161],
    

In [ ]:
np.min(arr10)
np.max(arr10)
np.sum(arr10)
np.mean(arr10)
np.median(arr10)
np.std(arr10)

224

In [ ]:
arr10.sort()           #in asscending order

None


In [109]:
arr11 = np.array([2, 5, 1, 9])
arr11.argsort()

array([2, 0, 1, 3], dtype=int64)

In [ ]:
list1 = [1, 2, 3, 4, 5] 

arr1 = np.array(list1).ndmin(4)

TypeError: 'int' object is not callable